version: 2
updates:
  - package-ecosystem: npm
    directory: '/tests/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
