name: Trivy Container Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '26 17 * * 3'

jobs:
  build:
    name: Trivy Container Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions: [
          { distribution: 'ubuntu', dist_version_code: 'noble', ubuntu_version_code: 'noble', tag: 'noble' },
          { distribution: 'ubuntu', dist_version_code: 'jammy', ubuntu_version_code: 'jammy', tag: 'jammy' },
          { distribution: 'ubuntu', dist_version_code: 'noble', ubuntu_version_code: 'noble', tag: 'latest' },
          { distribution: 'debian', dist_version_code: 'bookworm', ubuntu_version_code: 'jammy', tag: 'bookworm' }
        ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Build an image from Dockerfile
        if: ${{ always() }}
        env:
          IMAGRE_NAME: docker.io/poad/docker-zsh:${{ matrix.versions.tag }}
          DOCKER_BUILDKIT: 1
        run: |
          CUR=$(pwd) && \
          docker build \
            -t ${IMAGRE_NAME} \
            --build-arg DISTRIBUTION=${{ matrix.versions.distribution }} \
            --build-arg DIST_VERSION_CODE=${{ matrix.versions.dist_version_code }} \
            --build-arg UBUNTU_VERSION_CODE=${{ matrix.versions.ubuntu_version_code }} \
            -f ${{ matrix.versions.distribution }}/Dockerfile \
            . && \
          cd ${CUR}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        if: ${{ always() }}
        with:
          image-ref: docker.io/poad/docker-zsh:${{ matrix.versions.tag }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
